module.exports = {
  Docs: [
    {
      type: 'link',
      label: 'ThreePhotos',
      href: '/threePhotos',
    },
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
};
